insert into users (first_name, last_name, email, password, avatar, location, description, active) values ('Test', 'FreeFlow', 'test@freeflow.ca', 'password', 'https://robohash.org/eosporroillo.jpg?size=50x50&set=set1', 'San José de Jáchal', 'Multi-lateral non-volatile matrices', true),
('Eben', 'Houldey', 'ehouldey0@liveinternet.ru', 'NdWSaO5t', 'https://robohash.org/eosporroillo.jpg?size=50x50&set=set1', 'San José de Jáchal', 'Multi-lateral non-volatile matrices', true),
('Boyce', 'Dunbleton', 'bdunbleton1@mtv.com', 'U5wr4i2cIB8', 'https://robohash.org/fugiatnamconsequatur.bmp?size=50x50&set=set1', 'Gilowice', 'Persistent optimal benchmark', true),
('Hildegarde', 'Fahy', 'hfahy2@csmonitor.com', 'FfdrTbEW', 'https://robohash.org/velitetaliquid.jpg?size=50x50&set=set1', 'Ash Shawātī', 'Programmable optimal firmware', true),
('Mariel', 'Jarry', 'mjarry3@imgur.com', 'KTONLVv', 'https://robohash.org/temporaillodolore.png?size=50x50&set=set1', 'Aubervilliers', 'Polarised directional capability', false),
('Ferris', 'Mackrill', 'fmackrill4@mapquest.com', 'SIC4Qu6', 'https://robohash.org/consequaturdictavoluptatem.jpg?size=50x50&set=set1', 'Lorraine', 'Fundamental encompassing open architecture', true),
('Catherina', 'Louch', 'clouch5@mail.ru', 'AXJGKUThtEA', 'https://robohash.org/quissitomnis.jpg?size=50x50&set=set1', 'Zyuzino', 'Balanced heuristic infrastructure', true),
('Barris', 'Zelner', 'bzelner6@un.org', 'zEAdmkHDZ', 'https://robohash.org/quasharuminventore.jpg?size=50x50&set=set1', 'El Hajeb', 'Cross-group bifurcated functionalities', false),
('Beatrisa', 'Duchateau', 'bduchateau7@webs.com', 'q3nXCB0s', 'https://robohash.org/iustoquaeamet.jpg?size=50x50&set=set1', 'Semikarakorsk', 'Re-contextualized foreground concept', false),
('Benny', 'Gilvary', 'bgilvary8@typepad.com', '2tAYS7z0', 'https://robohash.org/maximesuscipitqui.png?size=50x50&set=set1', 'Káto Miliá', 'Digitized didactic portal', false),
('Langsdon', 'Roseaman', 'lroseaman9@dagondesign.com', 'dQYDhdMITgQa', 'https://robohash.org/inperferendisveniam.png?size=50x50&set=set1', 'Rudniki', 'Optional 24/7 forecast', true),
('Yorke', 'Dwelly', 'ydwellya@google.com.au', 'jX7pQrv', 'https://robohash.org/pariaturquisdicta.png?size=50x50&set=set1', 'Ylihärmä', 'Versatile even-keeled algorithm', false),
('Kimbell', 'Caves', 'kcavesb@google.ru', 'cmwIuqX1xJ6', 'https://robohash.org/velexcepturierror.png?size=50x50&set=set1', 'Sidi Smaïl', 'Sharable next generation methodology', false),
('Torry', 'Stronge', 'tstrongec@topsy.com', 'wtaxUh', 'https://robohash.org/perspiciatisquoquibusdam.png?size=50x50&set=set1', 'Bolilao', 'Quality-focused scalable archive', false),
('Perkin', 'Dilleway', 'pdillewayd@youtu.be', 'EZ10z1', 'https://robohash.org/quiculpaincidunt.jpg?size=50x50&set=set1', 'Guayabo Dulce', 'De-engineered value-added workforce', false),
('Nikki', 'Trinkwon', 'ntrinkwone@youtu.be', 'oaqoteeia', 'https://robohash.org/nonoccaecatiet.bmp?size=50x50&set=set1', 'Stepanovićevo', 'Organic bi-directional Graphical User Interface', false),
('Winfield', 'McKeever', 'wmckeeverf@arstechnica.com', 'mxVXpuUI', 'https://robohash.org/ininventoread.jpg?size=50x50&set=set1', 'Hanjia', 'Realigned static instruction set', false),
('Andeee', 'Waldren', 'awaldreng@phpbb.com', 'r4ZTnlb', 'https://robohash.org/etconsequaturamet.png?size=50x50&set=set1', 'Balneário Camboriú', 'Integrated intangible projection', true),
('Brittany', 'Dubique', 'bdubiqueh@chicagotribune.com', 'Z8VPkKzxVl', 'https://robohash.org/natusautemest.jpg?size=50x50&set=set1', 'Mayisyan', 'Enhanced 3rd generation projection', true),
('Germaine', 'Wallbank', 'gwallbanki@alibaba.com', 'D5YuDn', 'https://robohash.org/rerumnostrumsit.bmp?size=50x50&set=set1', 'Goúvai', 'Ergonomic object-oriented firmware', true),
('Candi', 'Plumm', 'cplummj@domainmarket.com', 'AzHYyIe00m', 'https://robohash.org/numquamrerumcumque.jpg?size=50x50&set=set1', 'Yangmiao', 'Programmable content-based website', true)